import type { NewOutletDraft } from "./newOutletTypes";

export function createDefaultNewOutletDraft(): NewOutletDraft {
  return {
    collectionProjectId: null,
    collectionProjectName: "",
    branchId: null,
    branchName: "",
    countyId: null,
    countyName: "",
    wardId: null,
    wardName: "",
    questionnaireId: null,
    typeOfAccount: "",
    medicalFacilityStatus: "",
    outletServicedByMed: "",
    selectedCategory: "",
    facilityName: "",
    ownerName: "",
    businessPhone: "",
    alternativePhone: "",
    email: "",
    physicalLocation: "",
    landmark: "",
    gps: "",
    accuracyMeters: 0,
    latitude: 0,
    longitude: 0,
    gpsCapturedAt: "",
    capturedPlaceName: "",
    reverseGeocodedAddress: "",
    capturedAddress: "",
    road: "",
    suburb: "",
    capturedWard: "",
    capturedCounty: "",
    region: "",
    country: "",
    photos: [],
    remarks: "",
  };
}
